site_name: Capyboard
repo_url: https://github.com/realcharmer/capyboard-docs
repo_name: realcharmer/capyboard-docs

plugins:
  - search
  - awesome-pages

theme:
  name: material
  language: en
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
